// <auto-generated />
using System;
using FileSortService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FileSortService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FileSortService.Model.DatabaseModel.ExtensionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nameCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExtenCategory");
                });

            modelBuilder.Entity("FileSortService.Model.DatabaseModel.ExtensionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("extensionCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("extensionValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("extensionCategoryId");

                    b.ToTable("ExtenValue");
                });

            modelBuilder.Entity("FileSortService.Model.DatabaseModel.ExtensionValue", b =>
                {
                    b.HasOne("FileSortService.Model.DatabaseModel.ExtensionCategory", "extensionCategory")
                        .WithMany()
                        .HasForeignKey("extensionCategoryId");

                    b.Navigation("extensionCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
